name: Assemble Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"
        cache: "gradle"

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Assemble project (release)
      run: ./gradlew assemble
